# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddProd.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from models import Product
from helpers.conversion import int2, float2


class AddProdScreen(object):
    def __init__(self, dialog: QtWidgets.QDialog) -> None:
        self.setupUi(dialog)
        self.frame = dialog
        self.onAddPress = None
        self.resultProd = Product()
        # __init__


    def handleAddClick(self, event):
        if self.onAddPress: self.onAddPress(self.resultProd)
        self.frame.accept()
        # handleAddClick


    def handleCancelClick(self, event):
        self.frame.reject()
        # handleCancelClick


    def updateAmt(self, qty: int = None, cost: float = None):
        if qty is None:
            qty = int2(self.qtyLineEdit.text())
        if cost is None:
            cost = float2(self.costLineEdit.text())
        
        self.amtLineEdit.setText(str(cost*qty))
        self.amtLineEdit.textEdited.emit(str(cost*qty))
        # updateAmt


    def updateTotal(self, amt: float = None, tax: float = None):
        if amt is None:
            amt = float2(self.amtLineEdit.text())
        if tax is None:
            tax = float2(self.taxLineEdit.text())

        self.totalLineEdit.setText(str(tax+amt))
        self.totalLineEdit.textEdited.emit(str(tax+amt))
        # updateTotal


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(621, 367)

        self.addBtn = QtWidgets.QPushButton(Form)
        self.addBtn.setGeometry(QtCore.QRect(330, 300, 87, 27))
        self.addBtn.clicked.connect(self.handleAddClick)
        self.addBtn.setObjectName("addBtn")

        self.cancelBtn = QtWidgets.QPushButton(Form)
        self.cancelBtn.setGeometry(QtCore.QRect(200, 300, 87, 27))
        self.cancelBtn.clicked.connect(self.handleCancelClick)
        self.cancelBtn.setObjectName("cancelBtn")

        # 

        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 50, 66, 19))
        self.label.setObjectName("label")

        self.productLineEdit = QtWidgets.QLineEdit(Form)
        self.productLineEdit.setGeometry(QtCore.QRect(170, 50, 113, 27))
        self.productLineEdit.textEdited.connect(lambda value: self.resultProd.setProduct(value))
        self.productLineEdit.setObjectName("productLineEdit")

        #

        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(70, 90, 66, 19))
        self.label_2.setObjectName("label_2")

        self.dateLineEdit = QtWidgets.QLineEdit(Form)
        self.dateLineEdit.setGeometry(QtCore.QRect(170, 90, 113, 27))
        self.dateLineEdit.textEdited.connect(lambda value: self.resultProd.setDate(value))
        self.dateLineEdit.setObjectName("dateLineEdit")

        #

        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(350, 50, 66, 19))
        self.label_3.setObjectName("label_3")

        self.regionLineEdit = QtWidgets.QLineEdit(Form)
        self.regionLineEdit.setGeometry(QtCore.QRect(450, 50, 113, 27))
        self.regionLineEdit.textEdited.connect(lambda value: self.resultProd.setRegion(value))
        self.regionLineEdit.setObjectName("lineEdit")

        #

        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(70, 130, 66, 19))
        self.label_4.setObjectName("label_4")

        self.qtyLineEdit = QtWidgets.QLineEdit(Form)
        self.qtyLineEdit.setGeometry(QtCore.QRect(170, 130, 113, 27))
        self.qtyLineEdit.textEdited.connect(lambda value: self.resultProd.setQty(int2(value)) or self.updateAmt(qty=int2(value)))
        self.qtyLineEdit.setObjectName("qtyLineEdit")

        #

        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(70, 170, 66, 19))
        self.label_5.setObjectName("label_5")

        self.costLineEdit = QtWidgets.QLineEdit(Form)
        self.costLineEdit.setGeometry(QtCore.QRect(170, 170, 113, 27))
        self.costLineEdit.textEdited.connect(lambda value: self.resultProd.setCost(float2(value)) or  self.updateAmt(cost=float2(value)))
        self.costLineEdit.setObjectName("costLineEdit")

        #

        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(350, 170, 66, 19))
        self.label_6.setObjectName("label_6")

        self.amtLineEdit = QtWidgets.QLineEdit(Form)
        self.amtLineEdit.setGeometry(QtCore.QRect(450, 170, 113, 27))
        self.amtLineEdit.textEdited.connect(lambda value: self.resultProd.setAmt(float2(value)) or self.updateTotal(amt=float2(value)))
        self.amtLineEdit.setEnabled(False)
        self.amtLineEdit.setObjectName("amtLineEdit")

        #

        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(70, 210, 66, 19))
        self.label_7.setObjectName("label_7")

        self.taxLineEdit = QtWidgets.QLineEdit(Form)
        self.taxLineEdit.setGeometry(QtCore.QRect(170, 210, 113, 27))
        self.taxLineEdit.textEdited.connect(lambda value: self.resultProd.setTax(float2(value)) or self.updateTotal(tax=float2(value)))
        self.taxLineEdit.setObjectName("taxLineEdit")

        #

        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(350, 210, 66, 19))
        self.label_8.setObjectName("label_8")

        self.totalLineEdit = QtWidgets.QLineEdit(Form)
        self.totalLineEdit.setGeometry(QtCore.QRect(450, 210, 113, 27))
        self.totalLineEdit.textEdited.connect(lambda value: self.resultProd.setTotal(float2(value)))
        self.totalLineEdit.setEnabled(False)
        self.totalLineEdit.setObjectName("totalLineEdit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        # setupUi


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Add Product"))

        self.addBtn.setText(_translate("Form", "Add"))
        self.cancelBtn.setText(_translate("Form", "Cancel"))

        self.label.setText(_translate("Form", "Product"))
        self.label_2.setText(_translate("Form", "Date"))
        self.label_3.setText(_translate("Form", "Region"))
        self.label_4.setText(_translate("Form", "Qty"))
        self.label_5.setText(_translate("Form", "Cost"))
        self.label_6.setText(_translate("Form", "Amt"))
        self.label_7.setText(_translate("Form", "Tax"))
        self.label_8.setText(_translate("Form", "Total"))
        # retranslateUi
